apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jin00100/argocd-advanced-lab.git' # 替换为你的仓库地址
    targetRevision: HEAD
    path: kustomize-guestbook/overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
